import type { Quote } from '../types'

export const DEMO_QUOTES: Quote[] = [
  {
    id: 'A1B2C',
    type: 'dom',
    addr: 'ul. Świdnicka 14, Wrocław',
    value: 650000,
    material: 'mur',
    year: 1980,
    area: 165,
    floodZone: 'Q500',
    alarm: true,
    monitoring: false,
    doors: true,
    fire: false,
    covs: ['mury', 'oc', 'kradziez', 'zalanie', 'assistance'],
    annual: 1847,
    status: 'contact',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'X9Y3Z',
    type: 'mieszkanie',
    addr: 'ul. Marszałkowska 110, Warszawa',
    value: 480000,
    material: 'mur',
    year: 1998,
    area: 68,
    floodZone: 'brak',
    alarm: false,
    monitoring: false,
    doors: false,
    fire: false,
    covs: ['mury', 'oc', 'szyby'],
    annual: 892,
    status: 'new',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'K7L4M',
    type: 'dom',
    addr: 'ul. Gdańska 3, Kraków',
    value: 890000,
    material: 'mur',
    year: 2015,
    area: 210,
    floodZone: 'brak',
    alarm: true,
    monitoring: true,
    doors: true,
    fire: true,
    covs: ['mury', 'ruchomosci', 'oc', 'kradziez', 'assistance', 'wandalizm'],
    annual: 2341,
    status: 'closed',
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
]
